ALTER TABLE users
    ADD COLUMN IF NOT EXISTS phone VARCHAR(50),
    ADD COLUMN IF NOT EXISTS birthday VARCHAR(50),
    ADD COLUMN IF NOT EXISTS address VARCHAR(255),
    ADD COLUMN IF NOT EXISTS city VARCHAR(120),
    ADD COLUMN IF NOT EXISTS zip_code VARCHAR(30),
    ADD COLUMN IF NOT EXISTS country VARCHAR(80),
    ADD COLUMN IF NOT EXISTS organization VARCHAR(180),
    ADD COLUMN IF NOT EXISTS department VARCHAR(180),
    ADD COLUMN IF NOT EXISTS timezone VARCHAR(60) NOT NULL DEFAULT 'UTC',
    ADD COLUMN IF NOT EXISTS locale VARCHAR(20) NOT NULL DEFAULT 'en';
